cargo-features = ["codegen-backend", "profile-rustflags"]

[workspace]
members = ['web', 'db', 'config']
resolver = '2'

[profile.dev]
codegen-backend = "cranelift"
rustflags = ["-Z", "threads=8"]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.test]
opt-level = 1
