[server]
port = 8080
ip = "127.0.0.1"
host = "http://localhost"

[tracing]
enable = true
env_filter = "nohead_rs=debug,tower_http=debug,axum::rejection=trace"

[database]
uri = "sqlite://db/nohead_rs.db"

[static_assets]
precompressed = false
path = "static"

[templates]
path = "templates"

[wasm_components]
path = "wasm"

[mailer]
base_url = "https://api.resend.com"
sender = "dev@notebar.io"
timeout = 2000
