[server]
port = 8080
ip = "127.0.0.1"

[tracing]
enable = true
env_filter = "nohead_rs=debug,tower_http=debug,axum::rejection=trace"

[database]
uri = "sqlite://db/nohead_rs.db"

[static_assets]
precompressed = false
path = "static"
