[server]
port = 8080
ip = "127.0.0.1"
#FIX: Add url to the server so it can be accessed in mailer config

[tracing]
enable = true
env_filter = "nohead_rs=debug,tower_http=debug,axum::rejection=trace"

[database]
uri = "sqlite://db/nohead_rs.db"

[static_assets]
precompressed = false
path = "static"

[mailer]
base_url = "https://api.resend.com"
sender = "dev@notebar.io"
timeout = 2000
