[server]
port = 8080
ip = "0.0.0.0"
host = "http://localhost"

[tracing]
enable = true
env_filter = "nohead_rs=debug,tower_http=debug,axum::rejection=trace"

[database]
uri = "sqlite://../db/nohead_rs__test.db"

[static_assets]
precompressed = false
path = "static"

[templates]
path = "templates"

[wasm_components]
path = "wasm"

[mailer]
base_url = "SET_BY_WIREMOCK_IN_TEST_ENVIRONMENT"
sender = "dev@notebar.io"
timeout = 2000
